# This is the configuration file for the example website of the Hugo theme
# Astatine (see https://github.com/hugcis/hugo-astatine-theme).
#
# The URL from which the site will be served
baseurl = "https://amirhnajafiz.github.io/"
# Language used
languageCode = "en-us"
# Website title
title = "AH. Najafizadeh"
# Theme used
# theme = "hugo-astatine-theme"

preserveTaxonomyNames = true
rssLimit = 10
paginate = 10

# Code highlighting
pygmentsCodefences = true
pygmentsStyle = "native"

# Taxonomies (only tags and categories are supported out of the box but you can
# add more)
[taxonomies]

# Configure permalinks style
[permalinks]
    post = "/:slug/"
    page = "/:slug/"

# Configure main navbar links. They can have a weight to select the order.
# This links to content within the content/post/ folder
[[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = -150

[[menu.main]]
    name = "Honors"
    url = "/honors/"
    weight = -200

[[menu.main]]
    name = "Research"
    url = "/research/"
    weight = -120

# This links to the page about.md
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = -110

# Site wide params and SEO
[params]
    # Site description. Individual pages can have descriptions too but if
    # missing it will fallback to that one.
    description = """My personal, academic, and educational website"""
    # Author of the site
    authorName = "amirhnajfiz"
    # Main image for the author. This will be the default image for SEO.
    [params.imgname]
        name = "https://avatars.githubusercontent.com/u/58415967?v=4"
        # Add an alt description for the image
        alt = "profile picture"

    # Indicate if you host Katex yourself. Defaults to using the CDN KaTex.
    # hostedKaTex = false

    # Optional: add a twitter handle and mastodon handle for SEO.
    # [params.twitter]
        # name = "@Jack_harkness"
    # [params.mastodon]
        # name = "@jkharkness"
        # host = "mastodon.social"
    
    # Enable link to feed in footer
    blogrss = true

    # Enable pingback and webmention via webmention.io
    # webmention = "hugocisneros.com"


# Sitemap location (default is /sitemap.xml)
[sitemap]
  filename = "sitemap.xml"
